/**
 * Every colour the app draws with, in both schemes, for every pack.
 * Deliberately free of React and React Native so the palettes can be checked
 * by tests that do not need a device: `theme.tsx` re-exports all of this and
 * adds the provider around it.
 */
export type ThemePreference = 'system' | 'light' | 'dark';

/**
 * Whether the dark palette applies: the preference when it states one, else
 * the system's answer. A system that states nothing (React Native types the
 * scheme as possibly null) resolves to dark, the way every sibling app
 * resolves it; in practice only a test renderer answers null, since
 * react-native-web answers light when `matchMedia` is absent.
 */
export function isDarkScheme(preference: ThemePreference, system: string | null | undefined): boolean {
  return preference === 'dark' || (preference === 'system' && system !== 'light');
}

export const lightColors = {
  background: '#f4f5f9',
  surface: '#ffffff',
  text: '#1c2130',
  textMuted: '#646b78',
  primary: '#3556da',
  primarySoft: '#dbe4ff',
  onPrimary: '#ffffff',
  accent: '#f59f00',
  accentSoft: '#fff3bf',
  /** Text and icons drawn on the accent, which is light in some packs and dark in others. */
  danger: '#c11d1d',
  dangerSoft: '#ffe3e3',
  success: '#15842a',
  successSoft: '#d3f9d8',
  line: '#c6cad4',
  lineStrong: '#1c2130',
  given: '#1c2130',
  entry: '#3556da',
  cellSelected: '#d1e0ff',
  cellPeer: '#e9ecf7',
  cellSameDigit: '#fde68a',
  cellConflict: '#ffd6d6',
  cellPhantom: '#ede9fe',
  phantom: '#7c3aed',
  shiftBanner: '#1c2130',
  onBanner: '#ffffff',
  onBannerMuted: '#c7cad3',
  backdrop: 'rgba(0,0,0,0.45)',
  onAccent: '#1c2130',
};

export type Colors = typeof lightColors;

export const darkColors: Colors = {
  background: '#0f1117',
  surface: '#1a1d27',
  text: '#e6e8ef',
  textMuted: '#9aa0b0',
  primary: '#869bff',
  primarySoft: '#2a3566',
  onPrimary: '#0f1117',
  accent: '#fbbf24',
  accentSoft: '#3d3116',
  danger: '#f87b7b',
  dangerSoft: '#4a1d1d',
  success: '#4ade80',
  successSoft: '#14351f',
  line: '#343a4a',
  lineStrong: '#e6e8ef',
  given: '#e6e8ef',
  entry: '#8ea2ff',
  cellSelected: '#1e2d8a',
  cellPeer: '#232838',
  cellSameDigit: '#463600',
  cellConflict: '#5a2323',
  cellPhantom: '#2d2547',
  phantom: '#b794f6',
  shiftBanner: '#232838',
  onBanner: '#ffffff',
  onBannerMuted: '#9aa0b0',
  backdrop: 'rgba(0,0,0,0.6)',
  onAccent: '#0f1117',
};

/**
 * A theme pack is a pair of palettes. Each is written as a short set of
 * overrides on the classic light or dark palette, so a pack only has to name
 * the colours that make it distinctive.
 */
export interface ThemePack {
  id: string;
  name: string;
  description: string;
  light: Colors;
  dark: Colors;
}

const light = (o: Partial<Colors>): Colors => ({ ...lightColors, ...o });
const dark = (o: Partial<Colors>): Colors => ({ ...darkColors, ...o });

export const THEME_PACKS: ThemePack[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'The original ink and indigo.',
    light: lightColors,
    dark: darkColors,
  },
  {
    id: 'paper',
    name: 'Paper',
    description: 'Warm newsprint and a red pencil.',
    light: light({
      background: '#f3ece1',
      surface: '#fdfaf4',
      text: '#2b2620',
      textMuted: '#70675b',
      primary: '#a4442f',
      primarySoft: '#f4dcd4',
      accent: '#986e23',
      accentSoft: '#f6e7c8',
      line: '#d3c7b4',
      lineStrong: '#2b2620',
      given: '#2b2620',
      entry: '#a4442f',
      cellSelected: '#fcd9cc',
      cellPeer: '#f0e7d9',
      cellSameDigit: '#f4dfad',
      cellConflict: '#fed7d0',
      cellPhantom: '#e9dfd0',
      phantom: '#6f624c',
      shiftBanner: '#2b2620',
      onBannerMuted: '#c9bfb0',
    
      onAccent: '#ffffff',
}),
    dark: dark({
      background: '#1a1713',
      surface: '#241f19',
      text: '#efe6d8',
      textMuted: '#a59885',
      primary: '#e38c6e',
      primarySoft: '#4a2a1e',
      onPrimary: '#1a1713',
      accent: '#d9ad5e',
      accentSoft: '#3d3116',
      line: '#3d352b',
      lineStrong: '#efe6d8',
      given: '#efe6d8',
      entry: '#e38c6e',
      cellSelected: '#562f21',
      cellPeer: '#2c261f',
      cellSameDigit: '#473710',
      cellConflict: '#4d2620',
      cellPhantom: '#332a20',
      phantom: '#bda67f',
      shiftBanner: '#2c261f',
    
      danger: '#f97d7d',
      onAccent: '#1a1713',
}),
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Phosphor green on black.',
    light: light({
      background: '#e4ece2',
      surface: '#f4faf2',
      text: '#123018',
      textMuted: '#4d6f54',
      primary: '#177138',
      primarySoft: '#cbe8d3',
      accent: '#8a6b12',
      accentSoft: '#f0e6bd',
      line: '#b3c9b6',
      lineStrong: '#123018',
      given: '#123018',
      entry: '#177138',
      cellSelected: '#b8ecc8',
      cellPeer: '#dcebdc',
      cellSameDigit: '#eae3a8',
      cellConflict: '#ffd7d2',
      cellPhantom: '#d7e6d9',
      phantom: '#386f52',
      shiftBanner: '#123018',
      onBannerMuted: '#adc4b0',
    
      onAccent: '#ffffff',
}),
    dark: dark({
      background: '#050b06',
      surface: '#0c160d',
      text: '#8ef2a4',
      textMuted: '#5eac73',
      primary: '#38e07b',
      primarySoft: '#123a20',
      onPrimary: '#050b06',
      accent: '#d8e04a',
      accentSoft: '#31371a',
      danger: '#ff6b6b',
      line: '#1e3521',
      lineStrong: '#8ef2a4',
      given: '#8ef2a4',
      entry: '#38e07b',
      cellSelected: '#003c13',
      cellPeer: '#0f1f11',
      cellSameDigit: '#30350a',
      cellConflict: '#4a1c1c',
      cellPhantom: '#16281c',
      phantom: '#6fd6a8',
      shiftBanner: '#0f1f11',
      onBanner: '#8ef2a4',
      onBannerMuted: '#4f9a63',
    
      onAccent: '#050b06',
}),
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Draughtsman lines on cyanotype blue.',
    light: light({
      background: '#e8eef6',
      surface: '#f7fafd',
      text: '#12314f',
      textMuted: '#506b86',
      primary: '#1c65a3',
      primarySoft: '#cfe3f4',
      line: '#b6c9db',
      lineStrong: '#12314f',
      given: '#12314f',
      entry: '#1c65a3',
      cellSelected: '#c1e5ff',
      cellPeer: '#dfe9f4',
      cellSameDigit: '#f0dfa8',
      cellConflict: '#ffd6d6',
      cellPhantom: '#dde5f0',
      phantom: '#48688c',
      shiftBanner: '#12314f',
      onBannerMuted: '#adc0d3',
    
      onAccent: '#12314f',
}),
    dark: dark({
      background: '#0a2038',
      surface: '#103050',
      text: '#e4f0fb',
      textMuted: '#8fb0cc',
      primary: '#7fd4ff',
      primarySoft: '#1b4b74',
      onPrimary: '#0a2038',
      accent: '#ffd479',
      accentSoft: '#3d3416',
      line: '#25547e',
      lineStrong: '#e4f0fb',
      given: '#e4f0fb',
      entry: '#7fd4ff',
      cellSelected: '#0a4c7e',
      cellPeer: '#153c60',
      cellSameDigit: '#4a4318',
      cellConflict: '#5a2530',
      cellPhantom: '#1d3f5e',
      phantom: '#a9c8e6',
      shiftBanner: '#153c60',
    
      danger: '#faa2a2',
      onBannerMuted: '#9da3b2',
      onAccent: '#0a2038',
}),
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Dusk over a warm horizon.',
    light: light({
      background: '#fdf1ec',
      surface: '#fffaf7',
      text: '#3d2233',
      textMuted: '#845f71',
      primary: '#b52c55',
      primarySoft: '#fbd9e3',
      accent: '#e08a2e',
      accentSoft: '#fce7cb',
      line: '#e3c8cd',
      lineStrong: '#3d2233',
      given: '#3d2233',
      entry: '#b52c55',
      cellSelected: '#ffd5e6',
      cellPeer: '#fae5ea',
      cellSameDigit: '#fbdfae',
      cellConflict: '#ffd6d2',
      cellPhantom: '#f0e0ee',
      phantom: '#8b4f97',
      shiftBanner: '#3d2233',
      onBannerMuted: '#cbb0bd',
    
      onAccent: '#3d2233',
}),
    dark: dark({
      background: '#1b1020',
      surface: '#2a172e',
      text: '#f7e4ef',
      textMuted: '#b694a9',
      primary: '#ff7fa4',
      primarySoft: '#5a2340',
      onPrimary: '#1b1020',
      accent: '#ffb457',
      accentSoft: '#4a3016',
      line: '#472a49',
      lineStrong: '#f7e4ef',
      given: '#f7e4ef',
      entry: '#ff7fa4',
      cellSelected: '#5f2144',
      cellPeer: '#2f1c35',
      cellSameDigit: '#4f3411',
      cellConflict: '#5c2229',
      cellPhantom: '#3a2247',
      phantom: '#d3a2e0',
      shiftBanner: '#2f1c35',
    
      danger: '#f97d7d',
      onAccent: '#1b1020',
}),
  },
  {
    id: 'contrast',
    name: 'High contrast',
    description: 'Maximum separation, colourblind safe.',
    light: light({
      background: '#ffffff',
      surface: '#ffffff',
      text: '#000000',
      textMuted: '#454545',
      primary: '#0033cc',
      primarySoft: '#cfd9ff',
      accent: '#8a5a00',
      accentSoft: '#ffe9b8',
      danger: '#b00020',
      dangerSoft: '#ffd6dd',
      success: '#005c2e',
      line: '#8a8a8a',
      lineStrong: '#000000',
      given: '#000000',
      entry: '#0033cc',
      cellSelected: '#cde2ff',
      cellPeer: '#e6e6e6',
      cellSameDigit: '#ffe08a',
      cellConflict: '#ffd6e0',
      cellPhantom: '#e0d5f5',
      phantom: '#5b2d91',
      shiftBanner: '#000000',
      onBannerMuted: '#cccccc',
    
      onAccent: '#ffffff',
}),
    dark: dark({
      background: '#000000',
      surface: '#101010',
      text: '#ffffff',
      textMuted: '#b8b8b8',
      primary: '#8ab4ff',
      primarySoft: '#1f3a6b',
      onPrimary: '#000000',
      accent: '#ffd166',
      accentSoft: '#4a3a10',
      danger: '#ff8a9b',
      dangerSoft: '#5c1622',
      success: '#6ee7a0',
      line: '#6a6a6a',
      lineStrong: '#ffffff',
      given: '#ffffff',
      entry: '#8ab4ff',
      cellSelected: '#113c8a',
      cellPeer: '#242424',
      cellSameDigit: '#543e08',
      cellConflict: '#6b1f2c',
      cellPhantom: '#33245c',
      phantom: '#c9a8ff',
      shiftBanner: '#151515',
    
      onAccent: '#000000',
}),
  },
];

export function themePack(id: string): ThemePack {
  return THEME_PACKS.find((p) => p.id === id) ?? THEME_PACKS[0];
}
